# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

panel_iframe:
  windy:
    title: "天气"
    icon: mdi:weather-partly-cloudy
    url: https://embed.windy.com/embed2.html?lat=30.16&lon=120.12&detailLat=30.16&detailLon=120.12&zoom=8&level=surface&product=ecmwf&menu=&message=true&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1

calendar:
  - platform: caldav
    username: 670457194@qq.com
    password: unhe-yjml-dnsb-cfeq
    url: https://caldav.icloud.com

  - platform: ics_calendar
    calendars:
      - name: "二十四节气"
        url: https://raw.githubusercontent.com/KaitoHH/24-jieqi-ics/master/23_solar_terms_2015-01-01_2050-12-31.ics
        include_all_day: True

panel_custom:
  - name: amap-panel
    sidebar_title: 地图
    sidebar_icon: hass:map
    module_url: /local/amap/amap-panel.js
    trust_external_script: true
    config:
      key: "afab1993cbdf13fef11f562931d6a17f"

sensor:
  - platform: time_date

media_dirs:
  media: /media
  recording: /mnt/recordings
# 3D_iframe:
#   - name: amap-panel
#     sidebar_title: 我的家
#     sidebar_icon: hass:map
#     module_url: /local/amap/amap-panel.js
# type: picture-elements
#   image: 'https://pics6.baidu.com/feed/908fa0ec08fa513d428674bb4abd7cf6b3fbd980.jpeg@f_auto?token=df3ad902896642c1deb681099275e8d7'
# elements:
#   - type: image
#     entity: switch.zimi_dhkg01_0300_switch
#     name: 厨房
#     tap_action: none
#     hold_action: none
#     state_image:
#     "off": 'https://pics6.baidu.com/feed/908fa0ec08fa513d428674bb4abd7cf6b3fbd980.jpeg@f_auto?token=df3ad902896642c1deb681099275e8d7'
#     "on": 'https://pics6.baidu.com/feed/908fa0ec08fa513d428674bb4abd7cf6b3fbd980.jpeg@f_auto?token=df3ad902896642c1deb681099275e8d7'
#     unavailable: 'https://pics6.baidu.com/feed/908fa0ec08fa513d428674bb4abd7cf6b3fbd980.jpeg@f_auto?token=df3ad902896642c1deb681099275e8d7'
#     style:
#       top: 50%
#       left: 50%
#       width: 100%
