
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_iframe:
  windy:
    title: '天气'
    icon: mdi:weather-partly-cloudy
    url: https://embed.windy.com/embed2.html?lat=30.16&lon=120.12&detailLat=30.16&detailLon=120.12&zoom=8&level=surface&product=ecmwf&menu=&message=true&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=km%2Fh&metricTemp=%C2%B0C&radarRange=-1

# calendar:
#   - platform: caldav
#     username: u_yvqa1yjk
#     password: 3ozwgcjl
#     url: calendar.dingtalk.com

panel_custom:
  - name: amap-panel
    sidebar_title: 地图
    sidebar_icon: hass:map
    module_url: /local/amap/amap-panel.js
    trust_external_script: true
    config:
        key: 'afab1993cbdf13fef11f562931d6a17f'

sensor: 
  - platform: time_date
    